name: birthday_countdown
description: Birthday Countdown App
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_datetime_picker: ^1.2.5
  rapido: ^0.1.9
  shared_preferences: ^0.5.4+5

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
